/**
 * Container Setup
 *
 * Configures and initializes the DI container with all services.
 *
 * After scaffolding a provider (npm run scaffold:provider), register your
 * generated PROVIDER_CLIENT and PROVIDER_SERVICE here.
 *
 * See: docs/02-ARCHITECTURE.md for DI container patterns
 * See: docs/STRIPE-REFERENCE.md for a complete wiring example
 */

import { Container, ServiceToken, ServiceLifetime } from './container';
import { LogService } from '../services/log.service';
import { ConfigurationService } from '../services/config.service';
import { RootClient } from '../clients/root-client';

/**
 * Create and configure the application container.
 * Call this once at application startup.
 */
export function createContainer(): Container {
  const container = new Container();

  // ── Infrastructure ──────────────────────────────────────────────────────────

  container.register(
    ServiceToken.CONFIG_SERVICE,
    () => new ConfigurationService(),
    ServiceLifetime.SINGLETON
  );

  container.register(
    ServiceToken.LOG_SERVICE,
    (c) => {
      const config = c.resolve<ConfigurationService>(ServiceToken.CONFIG_SERVICE);
      return new LogService({ environment: config.get('environment') });
    },
    ServiceLifetime.SINGLETON
  );

  container.register(
    ServiceToken.ROOT_CLIENT,
    () => new RootClient(),
    ServiceLifetime.SINGLETON
  );

  // ── Payment Provider (generated by scaffold) ────────────────────────────────
  //
  // TODO: After running `npm run scaffold:provider`, register your provider:
  //
  // container.register(
  //   ServiceToken.PROVIDER_CLIENT,
  //   () => new (require('../clients/{provider}-client').default)(),
  //   ServiceLifetime.SINGLETON
  // );
  //
  // container.register(
  //   ServiceToken.PROVIDER_SERVICE,
  //   (c) => {
  //     const logService = c.resolve<LogService>(ServiceToken.LOG_SERVICE);
  //     const providerClient = c.resolve(ServiceToken.PROVIDER_CLIENT);
  //     const YourService = require('../services/{provider}.service').YourService;
  //     return new YourService(logService, providerClient);
  //   },
  //   ServiceLifetime.SINGLETON
  // );

  // ── Domain Services ─────────────────────────────────────────────────────────

  container.register(
    ServiceToken.ROOT_SERVICE,
    (c) => {
      const logService = c.resolve<LogService>(ServiceToken.LOG_SERVICE);
      const rootClient = c.resolve(ServiceToken.ROOT_CLIENT);
      // eslint-disable-next-line unicorn/prefer-module
      return new (require('../services/root.service').RootService)(logService, rootClient);
    },
    ServiceLifetime.SINGLETON
  );

  container.register(
    ServiceToken.RENDER_SERVICE,
    () => {
      // eslint-disable-next-line unicorn/prefer-module
      return new (require('../services/render.service').RenderService)();
    },
    ServiceLifetime.SINGLETON
  );

  // ── Controllers (generated by scaffold) ────────────────────────────────────
  //
  // TODO: Register controllers here after implementing them.
  // Example:
  // container.register(
  //   ServiceToken.PAYMENT_PAID_CONTROLLER,
  //   (c) => {
  //     const logService = c.resolve<LogService>(ServiceToken.LOG_SERVICE);
  //     const providerService = c.resolve(ServiceToken.PROVIDER_SERVICE);
  //     return new PaymentPaidController(logService, providerService);
  //   },
  //   ServiceLifetime.TRANSIENT
  // );

  return container;
}

// ── Singleton helpers ───────────────────────────────────────────────────────

let globalContainer: Container | null = null;

export function getContainer(): Container {
  if (!globalContainer) {
    globalContainer = createContainer();
  }
  return globalContainer;
}

export function setContainer(container: Container): void {
  globalContainer = container;
}

export function resetContainer(): void {
  globalContainer = null;
}
